#!/usr/bin/python

# Ubuntu/Debian script

import pyaudio,os
import speech_recognition as sr

# Use xdotool for mouse and keyboard control

def openchrome():
    os.system("google-chrome&")

def opendownloads():
    os.system("nautilus $HOME/Downloads/ &")

def opensearch():
    os.system("gnome-do")

def lockscreen():
    os.system("xdotool key super+l")

def deactivate():
    os.system('espeak -v mb-us1 -s 170 "goodbye"')

def goonline():
    os.system('espeak -v mb-us1 -s 170 "switching to betty"')

def validCommand(source):
    audio = r.listen(source)
    try:
        cmd = r.recognize_google(audio).lower()
        print(cmd)
        if   cmd == "open chrome"    : openchrome()
        elif cmd == "open downloads" : opendownloads()
        elif cmd == "open search"    : opensearch()
        elif cmd == "lock screen"    : lockscreen()
        elif cmd == "deactivate"     : deactivate()
        elif cmd == "go online"      : goonline()
        else : return False

    except sr.UnknownValueError : return False
    except sr.RequestError : print("+"),; return False

    deactivate()
    return True


def activate(source):
    audio = r.listen(source)
    try:
        cmd = r.recognize_google(audio).lower()
        if cmd == "activate" : 
            os.system('espeak -v mb-us1 -s 170 "listening"')
            while validCommand(source) == False : pass

    except sr.UnknownValueError : return
    except sr.RequestError : print("!")


if __name__ == "__main__":
    r = sr.Recognizer()
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source, duration = 1)
        while 1:
            activate(source)
